### ISSUE TITLE
Requires BeautifulSoup but does not install it

### ISSUE THREAD

**Issue by jruderman** [mozilla/mozcommitbuilder#19]
```
sudo pip install mozcommitbuilder --upgrade
```

followed by

```
mozcommitbuilder
```

gave me

```
Traceback (most recent call last):
  File "/usr/local/bin/mozcommitbuilder", line 8, in <module>
    load_entry_point('mozcommitbuilder==0.4.10', 'console_scripts', 'mozcommitbuilder')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 318, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2221, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/mozcommitbuilder/__init__.py", line 1, in <module>
    from builder import cli as buildercli
  File "/Library/Python/2.7/site-packages/mozcommitbuilder/builder.py", line 53, in <module>
    from utils import hgId, captureStdout, increment_day, cpuCount, getTestUrl, download_url, unzip, url_base
  File "/Library/Python/2.7/site-packages/mozcommitbuilder/utils.py", line 45, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
```

Seems to work after running

```
sudo pip install BeautifulSoup
```

**Comment by k0s** [comment]
Thanks for the find.  Should be fixed: https://github.com/mozilla/mozcommitbuilder/commit/9f40de9efda2afd28f765fcd2d707d1349f6acce
